name: Generate Interactive BOM
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up pythonv3
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          wget https://github.com/openscopeproject/InteractiveHtmlBom/releases/download/v2.6.0/InteractiveHtmlBom.zip
          unzip InteractiveHtmlBom.zip
      - name: Generating Interactive BOM
        run: |
          python3 InteractiveHtmlBom/generate_interactive_bom.py ./*.kicad_pcb